<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.208">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Otho Mantegazza">

<title>A Glimpse to Linear Models</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#linear-models" id="toc-linear-models" class="nav-link active" data-scroll-target="#linear-models"><span class="toc-section-number">1</span>  Linear Models</a></li>
  <li><a href="#packages" id="toc-packages" class="nav-link" data-scroll-target="#packages"><span class="toc-section-number">2</span>  Packages</a></li>
  <li><a href="#the-rice-dataset" id="toc-the-rice-dataset" class="nav-link" data-scroll-target="#the-rice-dataset"><span class="toc-section-number">3</span>  The rice dataset</a>
  <ul class="collapse">
  <li><a href="#load-and-check" id="toc-load-and-check" class="nav-link" data-scroll-target="#load-and-check"><span class="toc-section-number">3.1</span>  Load and check</a>
  <ul class="collapse">
  <li><a href="#read-the-data" id="toc-read-the-data" class="nav-link" data-scroll-target="#read-the-data"><span class="toc-section-number">3.1.1</span>  Read the data</a></li>
  <li><a href="#structure-of-the-data" id="toc-structure-of-the-data" class="nav-link" data-scroll-target="#structure-of-the-data"><span class="toc-section-number">3.1.2</span>  Structure of the data</a></li>
  <li><a href="#content-and-aim-of-the-data" id="toc-content-and-aim-of-the-data" class="nav-link" data-scroll-target="#content-and-aim-of-the-data"><span class="toc-section-number">3.1.3</span>  Content and aim of the data</a></li>
  </ul></li>
  <li><a href="#question" id="toc-question" class="nav-link" data-scroll-target="#question"><span class="toc-section-number">3.2</span>  Question</a></li>
  <li><a href="#visualize-the-data-first" id="toc-visualize-the-data-first" class="nav-link" data-scroll-target="#visualize-the-data-first"><span class="toc-section-number">3.3</span>  Visualize the data first</a></li>
  </ul></li>
  <li><a href="#a-syntax-for-models" id="toc-a-syntax-for-models" class="nav-link" data-scroll-target="#a-syntax-for-models"><span class="toc-section-number">4</span>  A syntax for models</a>
  <ul class="collapse">
  <li><a href="#generic-linear-regression" id="toc-generic-linear-regression" class="nav-link" data-scroll-target="#generic-linear-regression"><span class="toc-section-number">4.1</span>  Generic linear regression</a></li>
  </ul></li>
  <li><a href="#run-the-model" id="toc-run-the-model" class="nav-link" data-scroll-target="#run-the-model"><span class="toc-section-number">5</span>  Run the model</a>
  <ul class="collapse">
  <li><a href="#explore-the-results" id="toc-explore-the-results" class="nav-link" data-scroll-target="#explore-the-results"><span class="toc-section-number">5.1</span>  Explore the results</a>
  <ul class="collapse">
  <li><a href="#a-summary-of-the-results" id="toc-a-summary-of-the-results" class="nav-link" data-scroll-target="#a-summary-of-the-results"><span class="toc-section-number">5.1.1</span>  A summary of the results</a></li>
  <li><a href="#diagnostic-plots" id="toc-diagnostic-plots" class="nav-link" data-scroll-target="#diagnostic-plots"><span class="toc-section-number">5.1.2</span>  Diagnostic plots</a></li>
  </ul></li>
  <li><a href="#tidy-the-results-with-broom" id="toc-tidy-the-results-with-broom" class="nav-link" data-scroll-target="#tidy-the-results-with-broom"><span class="toc-section-number">5.2</span>  Tidy the results with <code>broom</code></a>
  <ul class="collapse">
  <li><a href="#glance-the-results-of-the-linear-regression" id="toc-glance-the-results-of-the-linear-regression" class="nav-link" data-scroll-target="#glance-the-results-of-the-linear-regression"><span class="toc-section-number">5.2.1</span>  Glance the results of the linear regression</a></li>
  <li><a href="#tidy-the-results-of-the-linear-regression" id="toc-tidy-the-results-of-the-linear-regression" class="nav-link" data-scroll-target="#tidy-the-results-of-the-linear-regression"><span class="toc-section-number">5.2.2</span>  Tidy the results of the linear regression</a></li>
  <li><a href="#augment-the-results-of-the-linear-regression" id="toc-augment-the-results-of-the-linear-regression" class="nav-link" data-scroll-target="#augment-the-results-of-the-linear-regression"><span class="toc-section-number">5.2.3</span>  Augment the results of the linear regression</a></li>
  </ul></li>
  <li><a href="#visualize-the-results-of-the-linear-regression" id="toc-visualize-the-results-of-the-linear-regression" class="nav-link" data-scroll-target="#visualize-the-results-of-the-linear-regression"><span class="toc-section-number">5.3</span>  Visualize the results of the linear regression</a></li>
  <li><a href="#conclusions-from-the-model-and-from-the-graph" id="toc-conclusions-from-the-model-and-from-the-graph" class="nav-link" data-scroll-target="#conclusions-from-the-model-and-from-the-graph"><span class="toc-section-number">5.4</span>  Conclusions from the model and from the graph</a></li>
  </ul></li>
  <li><a href="#multiple-regression" id="toc-multiple-regression" class="nav-link" data-scroll-target="#multiple-regression"><span class="toc-section-number">6</span>  Multiple regression</a>
  <ul class="collapse">
  <li><a href="#what-if-we-want-to-use-more-than-one-predictor" id="toc-what-if-we-want-to-use-more-than-one-predictor" class="nav-link" data-scroll-target="#what-if-we-want-to-use-more-than-one-predictor"><span class="toc-section-number">6.1</span>  What if we want to use more than one predictor</a></li>
  <li><a href="#comparing-models" id="toc-comparing-models" class="nav-link" data-scroll-target="#comparing-models"><span class="toc-section-number">6.2</span>  Comparing models</a></li>
  </ul></li>
  <li><a href="#tidymodels" id="toc-tidymodels" class="nav-link" data-scroll-target="#tidymodels"><span class="toc-section-number">7</span>  Tidymodels</a>
  <ul class="collapse">
  <li><a href="#example-with-linear-regression" id="toc-example-with-linear-regression" class="nav-link" data-scroll-target="#example-with-linear-regression"><span class="toc-section-number">7.1</span>  Example with linear regression</a></li>
  <li><a href="#a-unified-framework" id="toc-a-unified-framework" class="nav-link" data-scroll-target="#a-unified-framework"><span class="toc-section-number">7.2</span>  A unified framework</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">A Glimpse to Linear Models</h1>
<p class="subtitle lead"><a href="../index.html">Home</a> | <a href="https://mawazoinstitute.org/cbser-summer-school">CBSER Summer School by Mawazo Institute</a></p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Otho Mantegazza </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="linear-models" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Linear Models</h1>
<p>Linear model are historically the first type of supervised model that is encountered when studying statistical learning, and are still probably the most used in biology, ecology and plenty of other fields. The most simple form of linear model is linear regression.</p>
<p>You can use linear model to test if a combination of one or more predictor variables can “explain”, infer or predict a response variable.</p>
<p>For reference on linear models check:</p>
<ul>
<li>Chapters 3 to 7 of <a href="https://www.statlearning.com">ISLR</a>.</li>
<li>Chapters 16, 17 and 18 of <a href="http://rafalab.dfci.harvard.edu/dsbook/regression.html">Introduction to Data Science</a>.</li>
<li><a href="https://bookdown.org/pingapang9/linear_models_bookdown/">Analising Data Using Linear Models</a>, for students in social, behavioural and management science, by Stéphanie M. van den Berg, basically the whole book.</li>
</ul>
<p>Let’s try linear regression in R.</p>
</section>
<section id="packages" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Packages</h1>
<p>First let’s load a selection of packages that we have been using throughout the lessons.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(magrittr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tibble)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then, let’s load a couple of packages specific for statistical modeling from the <a href="https://www.tidymodels.org/">tidymodels</a> framework.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(parsnip)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And let’s tweak the ggplot theme so graphics are easier to read on this page.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_update</span>(<span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">15</span>),</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">15</span>),</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">15</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="the-rice-dataset" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> The rice dataset</h1>
<p>We will keep working on the <a href="https://academic.oup.com/jxb/article/70/20/5617/5538968">rice dataset</a>, introduced in the <a href="60-explorative-data-analysis.html#/practice-dataset">slides on explorative data analysis</a>.</p>
<section id="load-and-check" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="load-and-check"><span class="header-section-number">3.1</span> Load and check</h2>
<section id="read-the-data" class="level3" data-number="3.1.1">
<h3 data-number="3.1.1" class="anchored" data-anchor-id="read-the-data"><span class="header-section-number">3.1.1</span> Read the data</h3>
<p>I’ve mirrored the data on my instance of github, let’s read them from there.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>rice <span class="ot">&lt;-</span>  </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">paste0</span>(</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'https://raw.githubusercontent.com/othomantegazza'</span>,</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'/mawazo-summer-school/main/data-int/rice.csv'</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">read_delim</span>(<span class="at">delim =</span> <span class="st">';'</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  janitor<span class="sc">::</span><span class="fu">clean_names</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 1140 Columns: 18
── Column specification ────────────────────────────────────────────────────────
Delimiter: ";"
chr  (6): Id, Species, Accession Name, Origine Continent, Type (Wild/Cultiva...
dbl (12): Replicate_nb (1/2), Plant_nb (1 to 3), Panicle_nb (1 to 3), Rachis...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
</section>
<section id="structure-of-the-data" class="level3" data-number="3.1.2">
<h3 data-number="3.1.2" class="anchored" data-anchor-id="structure-of-the-data"><span class="header-section-number">3.1.2</span> Structure of the data</h3>
<p>Let’s also check how the data look like:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>rice</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,140 × 18
   id    species acces…¹ origi…² type_…³ sowin…⁴ repli…⁵ plant…⁶ panic…⁷ rachi…⁸
   &lt;chr&gt; &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;     &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
 1 Ob01  Ob      B197    Africa  Wild    Cali-C…       1       1       1    8.1 
 2 Ob01  Ob      B197    Africa  Wild    Cali-C…       1       1       2    6.51
 3 Ob01  Ob      B197    Africa  Wild    Cali-C…       1       1       3    4.67
 4 Ob01  Ob      B197    Africa  Wild    Cali-C…       1       2       1    5.96
 5 Ob01  Ob      B197    Africa  Wild    Cali-C…       1       2       2    5.99
 6 Ob01  Ob      B197    Africa  Wild    Cali-C…       1       2       3    6.23
 7 Ob01  Ob      B197    Africa  Wild    Cali-C…       1       3       1    5.54
 8 Ob01  Ob      B197    Africa  Wild    Cali-C…       1       3       2    4.15
 9 Ob01  Ob      B197    Africa  Wild    Cali-C…       1       3       3    4.71
10 Ob01  Ob      B197    Africa  Wild    Cali-C…       2       1       1    6.95
# … with 1,130 more rows, 8 more variables: primary_branch_number_pbn &lt;dbl&gt;,
#   average_of_primary_branch_length_in_cm_pbl &lt;dbl&gt;,
#   average_of_internode_along_primary_branch_in_cm_pbil &lt;dbl&gt;,
#   secondary_branch_number_sbn &lt;dbl&gt;,
#   average_of_secondary_branch_length_in_cm_sbl &lt;dbl&gt;,
#   average_of_internode_along_secondary_branch_in_cm_sbil &lt;dbl&gt;,
#   tertiary_branch_number_tbn &lt;dbl&gt;, spikelet_number_sp_n &lt;dbl&gt;, and …
# ℹ Use `print(n = ...)` to see more rows, and `colnames()` to see all variable names</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>rice <span class="sc">%&gt;%</span> <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1,140
Columns: 18
$ id                                                     &lt;chr&gt; "Ob01", "Ob01",…
$ species                                                &lt;chr&gt; "Ob", "Ob", "Ob…
$ accession_name                                         &lt;chr&gt; "B197", "B197",…
$ origine_continent                                      &lt;chr&gt; "Africa", "Afri…
$ type_wild_cultivated                                   &lt;chr&gt; "Wild", "Wild",…
$ sowing_localisation                                    &lt;chr&gt; "Cali-Colombia"…
$ replicate_nb_1_2                                       &lt;dbl&gt; 1, 1, 1, 1, 1, …
$ plant_nb_1_to_3                                        &lt;dbl&gt; 1, 1, 1, 2, 2, …
$ panicle_nb_1_to_3                                      &lt;dbl&gt; 1, 2, 3, 1, 2, …
$ rachis_length_rl_in_cm                                 &lt;dbl&gt; 8.10, 6.51, 4.6…
$ primary_branch_number_pbn                              &lt;dbl&gt; 5, 5, 4, 4, 4, …
$ average_of_primary_branch_length_in_cm_pbl             &lt;dbl&gt; 6.73, 6.26, 6.9…
$ average_of_internode_along_primary_branch_in_cm_pbil   &lt;dbl&gt; 2.03, 1.63, 1.5…
$ secondary_branch_number_sbn                            &lt;dbl&gt; 5, 3, 2, 5, 1, …
$ average_of_secondary_branch_length_in_cm_sbl           &lt;dbl&gt; 1.74, 1.51, 1.9…
$ average_of_internode_along_secondary_branch_in_cm_sbil &lt;dbl&gt; 0.99, 0.72, 1.6…
$ tertiary_branch_number_tbn                             &lt;dbl&gt; 0, 0, 0, 0, 0, …
$ spikelet_number_sp_n                                   &lt;dbl&gt; 38, 38, 30, 35,…</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>rice <span class="sc">%&gt;%</span> <span class="fu">count</span>(species)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  species     n
  &lt;chr&gt;   &lt;int&gt;
1 Ob        264
2 Og        370
3 Or        215
4 Os        291</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>rice <span class="sc">%&gt;%</span> <span class="fu">pull</span>(accession_name) <span class="sc">%&gt;%</span> <span class="fu">n_distinct</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 91</code></pre>
</div>
</div>
</section>
<section id="content-and-aim-of-the-data" class="level3" data-number="3.1.3">
<h3 data-number="3.1.3" class="anchored" data-anchor-id="content-and-aim-of-the-data"><span class="header-section-number">3.1.3</span> Content and aim of the data</h3>
<p>The dataset contains phenotypic measurements of 1140 rice panicle from 91 rice accessions of 4 different rice species.</p>
<p>The aim of <a href="https://academic.oup.com/jxb/article/70/20/5617/5538968">the paper in which this dataset is published</a> is to compare panicles at a phenotypic and transcriptomic level for a combination of 4 African and Asian, wild and domesticated rice species.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;">species_id</th>
<th style="text-align: left;">species</th>
<th style="text-align: left;">continent</th>
<th style="text-align: left;">status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Ob</td>
<td style="text-align: left;">Oryza barthii</td>
<td style="text-align: left;">African</td>
<td style="text-align: left;">Wild</td>
</tr>
<tr class="even">
<td style="text-align: left;">Og</td>
<td style="text-align: left;">Oryza glaberrima</td>
<td style="text-align: left;">African</td>
<td style="text-align: left;">Cultivated</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Or</td>
<td style="text-align: left;">Oryza rufipogon</td>
<td style="text-align: left;">Asian</td>
<td style="text-align: left;">Wild</td>
</tr>
<tr class="even">
<td style="text-align: left;">Os</td>
<td style="text-align: left;">Oryza sativa</td>
<td style="text-align: left;">Asian</td>
<td style="text-align: left;">Cultivated</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>In the picture below, from the <a href="https://academic.oup.com/jxb/article/70/20/5617/5538968">original article (<em>CC-BY-NC</em>)</a> you can find a graphical explanation of the phenotypic features measured in the rice dataset.</p>
<p><img src="img/rice-panicle.png" class="img-fluid"></p>
</section>
</section>
<section id="question" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="question"><span class="header-section-number">3.2</span> Question</h2>
<p>Let’s try to answer the question: Can we use the number of branches (PB e SB) on a panicle to explain the number of spikelets (SP) on the same panicle? In case how?</p>
</section>
<section id="visualize-the-data-first" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="visualize-the-data-first"><span class="header-section-number">3.3</span> Visualize the data first</h2>
<p>To answer the question, let’s first visualize the data to get an idea of how they are distributed.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>rice <span class="sc">%&gt;%</span> </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> primary_branch_number_pbn,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">y =</span> spikelet_number_sp_n,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">colour =</span> species)) <span class="sc">+</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> .<span class="dv">4</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="73-supervised_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>It seems that the number of spikelets grows with the number of primary branches on a panicle. The pattern might not be perfectly linear, and there might be some variation among different rice species.</p>
<p>Let’s also visualize the same data divided in facets, to get a clearer idea of how different species behave.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>rice <span class="sc">%&gt;%</span> </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> primary_branch_number_pbn,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">y =</span> spikelet_number_sp_n,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">colour =</span> species)) <span class="sc">+</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> .<span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="at">facets =</span> <span class="st">'species'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="73-supervised_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The data points are more dispersed vertically in Og (Oryza glaberrima) and Oryza sativa. Those two species are domesticated species, they produce many secondary branches, this “uncouples” the number of spikelets from the number of primary branches.</p>
<p>Can we describe this observation with a statistical model using linear regression?</p>
</section>
</section>
<section id="a-syntax-for-models" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> A syntax for models</h1>
<p>How do we define a model in R? Let’s start from a generic regression.</p>
<section id="generic-linear-regression" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="generic-linear-regression"><span class="header-section-number">4.1</span> Generic linear regression</h2>
<p>In a simple linear model, such as linear regression, we are modelling the response variable <code>Y</code> as a combination two coefficients <code>a</code> and <code>b</code> that define the intercept and the slope of the line, the predictor <code>X</code> and an <code>error</code> term that, in absence of a better explanation, we hypothesize as being random gaussian.</p>
<p><span class="math display">\[Y = a + b * X + error\]</span></p>
<p>We can express the same concept with a tilde <code>~</code> formula.</p>
<p><span class="math display">\[Y \sim a + b * X\]</span> If we substitute the generic terms of the equation above with the variables from the rice dataset, we can say that, in the rice problem, we are trying to guess the <code>intercept</code> and <code>slope</code> coefficients for this equation.</p>
<p><span class="math display">\[spikelets = intercept + slope * primary\_branches + error\]</span> Let’s use a tilde formula again.</p>
<p><span class="math display">\[spikelets \sim intercept + slope * primary\_branches\]</span></p>
<p>With this syntax we can express models with any number of predictors, or any mathematical combination of them.</p>
<p><span class="math display">\[Y = a + b_1X_1 + b\_2X_2 + ... + b\_nX_n + error\]</span> ## Model formulas in R</p>
<p>R has adopted the <a href="https://thomasleeper.com/Rcourse/Tutorials/formulae.html">tilde model formula definition</a> that we have seen above to define models within it’s function, such as <code>lm()</code>. So, for example, the formula: <code>spikelet_number_sp_n ~ primary_branch_number_pb</code> will use:</p>
<ul>
<li>The variable <code>spikelet_number_sp_n</code> as response.</li>
<li>The <code>primary_branch_number_pbn</code> as predictor.</li>
<li>The intercept and the slope get’s calculated automatically when we provide this formula and the associated data to the function <code>lm()</code></li>
</ul>
</section>
</section>
<section id="run-the-model" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Run the model</h1>
<p>We can declare and evaluate a linear model in R with the function <code>lm()</code>.</p>
<p>Let’s run it with the formula mentioned above on the <code>rice</code> data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">formula =</span> spikelet_number_sp_n <span class="sc">~</span> primary_branch_number_pbn,</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">data =</span> rice</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We have run a linear regression of <code>spikelet_number_sp_n</code> over <code>primary_branch_number_pbn</code>. And associated the results to the object <code>fit</code>. How do we see the results?</p>
<p>Just by calling the object fit, we can print on screen the slope and intercept estimated by the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>fit</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = spikelet_number_sp_n ~ primary_branch_number_pbn, 
    data = rice)

Coefficients:
              (Intercept)  primary_branch_number_pbn  
                   -20.44                      15.60  </code></pre>
</div>
</div>
<p>In the next sessions we will explore the many available tools to get more information and diagnostics from the model.</p>
<section id="explore-the-results" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="explore-the-results"><span class="header-section-number">5.1</span> Explore the results</h2>
<section id="a-summary-of-the-results" class="level3" data-number="5.1.1">
<h3 data-number="5.1.1" class="anchored" data-anchor-id="a-summary-of-the-results"><span class="header-section-number">5.1.1</span> A summary of the results</h3>
<p>The <a href="https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/summary.lm"><code>summary()</code></a> method prints:</p>
<ul>
<li>The <strong>coefficients</strong> that we’ve seen above (in this case the slope and the intercept of the linear regression line) with the associated T-statistics.</li>
<li><strong>R-squared</strong> and <strong>F-statistics</strong> measuring and scoring the overall model.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>fit <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = spikelet_number_sp_n ~ primary_branch_number_pbn, 
    data = rice)

Residuals:
    Min      1Q  Median      3Q     Max 
-134.11  -28.79  -11.35   19.07  209.47 

Coefficients:
                          Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)               -20.4391     4.0043  -5.104 3.89e-07 ***
primary_branch_number_pbn  15.5966     0.4102  38.023  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 50.08 on 1138 degrees of freedom
Multiple R-squared:  0.5596,    Adjusted R-squared:  0.5592 
F-statistic:  1446 on 1 and 1138 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="diagnostic-plots" class="level3" data-number="5.1.2">
<h3 data-number="5.1.2" class="anchored" data-anchor-id="diagnostic-plots"><span class="header-section-number">5.1.2</span> Diagnostic plots</h3>
<p>If you use the <a href="https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/plot.lm"><code>plot()</code></a> method on a fitted <code>lm</code> object, R prints a selection of <a href="https://www.r-bloggers.com/2019/11/the-hidden-diagnostic-plots-for-the-lm-object/">4 diagnostic plots</a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>)) <span class="co"># organize the plots in a 2x2 grid</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="73-supervised_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="tidy-the-results-with-broom" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="tidy-the-results-with-broom"><span class="header-section-number">5.2</span> Tidy the results with <code>broom</code></h2>
<p>To access the coefficients and statistics of the model systematically, what better choice than to tidy them in a tibble with the package <a href="https://broom.tidymodels.org/">broom</a></p>
<div class="columns">
<div class="column" style="width:40%;">
<p><img src="https://raw.githubusercontent.com/rstudio/hex-stickers/master/SVG/broom.svg" class="img-fluid"></p>
</div><div class="column" style="width:10%;">

</div><div class="column" style="width:50%;">
<p><a href="https://broom.tidymodels.org/">broom</a> summarizes key information about models in tidy <code>tibble()</code>s. broom provides three verbs to make it convenient to interact with model objects:</p>
<ul>
<li><code>tidy()</code> summarizes information about model components.</li>
<li><code>glance()</code> reports information about the entire model.</li>
<li><code>augment()</code> adds information about observations to a dataset.</li>
</ul>
</div>
</div>
<p>Let’s check broom’s main functions.</p>
<section id="glance-the-results-of-the-linear-regression" class="level3 scrollable" data-number="5.2.1">
<h3 class="scrollable anchored" data-number="5.2.1" data-anchor-id="glance-the-results-of-the-linear-regression"><span class="header-section-number">5.2.1</span> Glance the results of the linear regression</h3>
<p><code>glance()</code> reports information about the entire model, similar to what we have seen in the last lines of the output of <code>summary()</code>, but in a tibble.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>fit <span class="sc">%&gt;%</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glance</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1
Columns: 12
$ r.squared     &lt;dbl&gt; 0.5595511
$ adj.r.squared &lt;dbl&gt; 0.559164
$ sigma         &lt;dbl&gt; 50.08321
$ statistic     &lt;dbl&gt; 1445.727
$ p.value       &lt;dbl&gt; 7.518553e-205
$ df            &lt;dbl&gt; 1
$ logLik        &lt;dbl&gt; -6078.191
$ AIC           &lt;dbl&gt; 12162.38
$ BIC           &lt;dbl&gt; 12177.5
$ deviance      &lt;dbl&gt; 2854478
$ df.residual   &lt;int&gt; 1138
$ nobs          &lt;int&gt; 1140</code></pre>
</div>
</div>
</section>
<section id="tidy-the-results-of-the-linear-regression" class="level3 scrollable" data-number="5.2.2">
<h3 class="scrollable anchored" data-number="5.2.2" data-anchor-id="tidy-the-results-of-the-linear-regression"><span class="header-section-number">5.2.2</span> Tidy the results of the linear regression</h3>
<p><code>tidy()</code> summarizes information about model coefficients and their statistics in a tibble.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>fit_tidy <span class="ot">&lt;-</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  fit <span class="sc">%&gt;%</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>()</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>fit_tidy</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term                      estimate std.error statistic   p.value
  &lt;chr&gt;                        &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)                  -20.4     4.00      -5.10 3.89e-  7
2 primary_branch_number_pbn     15.6     0.410     38.0  7.52e-205</code></pre>
</div>
</div>
</section>
<section id="augment-the-results-of-the-linear-regression" class="level3 scrollable" data-number="5.2.3">
<h3 class="scrollable anchored" data-number="5.2.3" data-anchor-id="augment-the-results-of-the-linear-regression"><span class="header-section-number">5.2.3</span> Augment the results of the linear regression</h3>
<p><code>augment()</code> returns a tibble with the fitted and residuals values for every observation that was used to train the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>fit_augmented <span class="ot">&lt;-</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  fit <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>()</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>fit_augmented</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,140 × 8
   spikelet_number_sp_n primary_…¹ .fitted .resid    .hat .sigma .cooksd .std.…²
                  &lt;dbl&gt;      &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
 1                   38          5    57.5 -19.5  0.00199   50.1 1.52e-4 -0.391 
 2                   38          5    57.5 -19.5  0.00199   50.1 1.52e-4 -0.391 
 3                   30          4    41.9 -11.9  0.00260   50.1 7.44e-5 -0.239 
 4                   35          4    41.9  -6.95 0.00260   50.1 2.51e-5 -0.139 
 5                   22          4    41.9 -19.9  0.00260   50.1 2.07e-4 -0.399 
 6                   28          4    41.9 -13.9  0.00260   50.1 1.01e-4 -0.279 
 7                   34          4    41.9  -7.95 0.00260   50.1 3.29e-5 -0.159 
 8                   18          3    26.4  -8.35 0.00335   50.1 4.68e-5 -0.167 
 9                   29          3    26.4   2.65 0.00335   50.1 4.71e-6  0.0530
10                   38          6    73.1 -35.1  0.00151   50.1 3.72e-4 -0.702 
# … with 1,130 more rows, and abbreviated variable names
#   ¹​primary_branch_number_pbn, ²​.std.resid
# ℹ Use `print(n = ...)` to see more rows</code></pre>
</div>
</div>
</section>
</section>
<section id="visualize-the-results-of-the-linear-regression" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="visualize-the-results-of-the-linear-regression"><span class="header-section-number">5.3</span> Visualize the results of the linear regression</h2>
<p>Once we have extracted the model coefficients with broom, we can use ggplot to represent the regression line graphically.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>mod_intercept <span class="ot">&lt;-</span> fit_tidy <span class="sc">%&gt;%</span> <span class="fu">slice</span>(<span class="dv">1</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(estimate)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>mod_slope <span class="ot">&lt;-</span> fit_tidy <span class="sc">%&gt;%</span> <span class="fu">slice</span>(<span class="dv">2</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(estimate)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>rice <span class="sc">%&gt;%</span> </span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> primary_branch_number_pbn,</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">y =</span> spikelet_number_sp_n)) <span class="sc">+</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> .<span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> mod_intercept,</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>              <span class="at">slope =</span> mod_slope)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="73-supervised_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>It’s basically the same result that we get if we add a <code>geom_smooth()</code> to the graphic, with the parameter <code>method = 'lm'</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>rice <span class="sc">%&gt;%</span> </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> primary_branch_number_pbn,</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">y =</span> spikelet_number_sp_n)) <span class="sc">+</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> .<span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">'lm'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="73-supervised_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="conclusions-from-the-model-and-from-the-graph" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="conclusions-from-the-model-and-from-the-graph"><span class="header-section-number">5.4</span> Conclusions from the model and from the graph</h2>
<ul>
<li>The model suggests that the number of spikelets grows with the number of primary branches. More precisely, the model estimates that on average, you get 15.6 spikelets every new primary branch.</li>
<li>We can see visually that the variance of the response variable <code>spikelet_number_sp_n</code> grows when the predictor <code>primary_branch_number_pbn</code> grows. So at high number of primary branches we can expect our predictions of spikelet number to be more approximated.</li>
<li>You can see from the <a href="#diagnostic-plots">diagnostic plot</a>, that the relationship between number of spikelets and primary branches might not be perfectly linear. One educated hypothesis to explain this behaviour might be that the species that produce most spikelets rely heavily on secondary branches, and not only on primary branches.</li>
</ul>
</section>
</section>
<section id="multiple-regression" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Multiple regression</h1>
<section id="what-if-we-want-to-use-more-than-one-predictor" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="what-if-we-want-to-use-more-than-one-predictor"><span class="header-section-number">6.1</span> What if we want to use more than one predictor</h2>
<p>We can specify any type of formula, including as predictor both continuous and categorical variables or any type of mathematical transformation of such variables.</p>
<p>See chapter 3 and 7 of <a href="https://www.statlearning.com/">Introduction to Statistical Learning</a> to learn in detail about multiple regression and moving beyond linearity.</p>
<p>Let’s try to fit the spikelet number as a function of both primary and secondary branch number. To achieve this we can add the variable <code>secondary_branch_number_sbn</code> to the model formula that we have seen above.</p>
<p><code>spikelet_number_sp_n ~ primary_branch_number_pbn + secondary_branch_number_sbn</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>fit_multiple <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> spikelet_number_sp_n <span class="sc">~</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>    primary_branch_number_pbn <span class="sc">+</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>    secondary_branch_number_sbn,</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> rice)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s explore the results of the fit:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>fit_multiple <span class="sc">%&gt;%</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glance</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1
Columns: 12
$ r.squared     &lt;dbl&gt; 0.9525715
$ adj.r.squared &lt;dbl&gt; 0.9524881
$ sigma         &lt;dbl&gt; 16.44202
$ statistic     &lt;dbl&gt; 11417.96
$ p.value       &lt;dbl&gt; 0
$ df            &lt;dbl&gt; 2
$ logLik        &lt;dbl&gt; -4807.906
$ AIC           &lt;dbl&gt; 9623.811
$ BIC           &lt;dbl&gt; 9643.966
$ deviance      &lt;dbl&gt; 307376.4
$ df.residual   &lt;int&gt; 1137
$ nobs          &lt;int&gt; 1140</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>fit_multiple <span class="sc">%&gt;%</span> </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  term                        estimate std.error statistic  p.value
  &lt;chr&gt;                          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)                     4.72    1.34        3.52 4.43e- 4
2 primary_branch_number_pbn       4.13    0.179      23.0  1.00e-96
3 secondary_branch_number_sbn     4.09    0.0421     97.1  0       </code></pre>
</div>
</div>
<p>The p-value of the new term <code>secondary_branch_number_sbn</code> has an incredibly low p-value (approximated at 0), a hint that the this term is adding information to the model and is helping us building a better function that connects the spikelet number to the branch number.</p>
<p>We can use the diagnostic plot to check how this model is performing.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>)) <span class="co"># organize the plots in a 2x2 grid</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>fit_multiple <span class="sc">%&gt;%</span> <span class="fu">plot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="73-supervised_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>You can extend this reasoning to any variable in the dataset.</p>
<p>For example, try yourself to model the number of spikelet with this formula below, in which we add the variable as a new predictor <code>species</code>:</p>
<pre><code>spikelet_number_sp_n ~
   primary_branch_number_pbn +
   secondary_branch_number_sbn +
   species</code></pre>
</section>
<section id="comparing-models" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="comparing-models"><span class="header-section-number">6.2</span> Comparing models</h2>
<p>As our model become more and more nuanced and complicated, it gets harder to understand the output intuitively, and to visualize the results.</p>
<p>Thus it gets harder to answer vital questions such as:</p>
<ul>
<li>which combination and transformation of predictors should I include in the model,</li>
<li>which model is best to encapsulate the signal in my data, successfully excluding the noise.</li>
</ul>
<p>Predictor and model selection is an incredibly important and wide field in modelling and the method might change whether you’re aim is inference or prediction.</p>
<p>A very basic example of ways to compare similar model is to run an anova to check if the model with an added term is explaining more variance then the simpler one.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  fit, </span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  fit_multiple</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: spikelet_number_sp_n ~ primary_branch_number_pbn
Model 2: spikelet_number_sp_n ~ primary_branch_number_pbn + secondary_branch_number_sbn
  Res.Df     RSS Df Sum of Sq      F    Pr(&gt;F)    
1   1138 2854478                                  
2   1137  307376  1   2547101 9421.8 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>But you can learn more effective ways to select and test if your linear model is working properly in:</p>
<ul>
<li>Chapter 5 “Resampling Methods” and chapter 6 “Linear Model Selection and Regularization” of <a href="https://www.statlearning.com/">Introduction to Statistical Learning</a>.</li>
<li>Chapter 10 to 15 of <a href="https://www.tmwr.org/">Tidy Modeling with R</a>.</li>
</ul>
</section>
</section>
<section id="tidymodels" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Tidymodels</h1>
<p>We had a glimpse of what you can do in R with linear models.</p>
<p>The main function modeling function that we have used is <code>lm()</code> from the <a href="https://stat.ethz.ch/R-manual/R-devel/library/stats/html/00Index.html"><code>stats</code></a> package (which is loaded in R at start up, and that’s why we didn’t have to load it calling <code>library(stats)</code>).</p>
<p>R has many other packages dedicated to modeling, provided access to a multitude of advanced modeling methods, each with a dedicated interface and diagnostic tools.</p>
<p>To unify and ease access to this multitude and to encourage good modeling practices through suggested and standardized workflow, the R community recently published the <a href="https://www.tidymodels.org/"><code>tidymodels</code></a> framework.</p>
<p>Just as we load all tidyverse packages at once by calling <code>library(tidyverse)</code>, we can load every tidymodels package calling <code>library(tidymodels)</code> (remember that first you have to install them with <code>install.packages("tidymodels")</code>).</p>
<p>We have already used the <code>broom</code> package from tidymodels, installing it and loading it separately from the whole framework.</p>
<section id="example-with-linear-regression" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="example-with-linear-regression"><span class="header-section-number">7.1</span> Example with linear regression</h2>
<p>Let’s load also the tidymodels package <a href="https://parsnip.tidymodels.org/">parsnip</a> and use it to fit the same linear regression that we have seen above.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(parsnip)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>First let’s define a linear regression model and declare that we are using <code>lm()</code> as the modelling engine.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">'lm'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then, let’s fit the model</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>mod_fit <span class="ot">&lt;-</span> </span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  mod <span class="sc">%&gt;%</span> </span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">formula =</span> spikelet_number_sp_n <span class="sc">~</span> primary_branch_number_pbn,</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> rice</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(mod_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term                      estimate std.error statistic   p.value
  &lt;chr&gt;                        &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)                  -20.4     4.00      -5.10 3.89e-  7
2 primary_branch_number_pbn     15.6     0.410     38.0  7.52e-205</code></pre>
</div>
</div>
</section>
<section id="a-unified-framework" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="a-unified-framework"><span class="header-section-number">7.2</span> A unified framework</h2>
<p>We have achieved the same as when we where calling <code>lm()</code>. Although we have used more lines of code, if you get used to the tidymodels syntax, you will have access to advanced modeling methods and workflows easily, because the same standardized syntax will apply to all modeling methods that you want to apply.</p>
<p>Check the <a href="https://www.tmwr.org/index.html">Tidymodels with R</a> book to take your next step in the statistical modeling world with R.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>