---
title: 'Data Analysis in R'
subtitle: '[CBSER Summer School by RWTH Aachen and Mawazo Institute](https://mawazoinstitute.org/cbser-summer-school)'
author: 'Otho Mantegazza'
format:
  html:
    toc: true
---

# Slides

Introduction:

1. [Introduction](slides/00-intro.html)

Hands on data with R:

1. [Meet R](slides/10-meet-r.html)
1. [Manipulate Data](slides/20-manipulate.html)
1. [Missing Values](slides/25-missing-values.html)
1. [Visualize Data](slides/30-visualize.html)
1. [Notes on Correlation](slides/31-correlation.html)
1. [Robust Statistics](slides/31-robust-stat.html)
1. [Get Data into R](slides/40-get.html)
1. [Clean Data with R](slides/50-clean.html)
1. [Explorative Data Analysis](slides/60-explorative-data-analysis.html)

Explore your data with statistical models:

1. [A Few Words on Statistical Models](slides/70-intro-to-models.html)
1. [Supervised Learning - A glimpse to Linear Models and an introduction to Tidymodels](slides/73-supervised.qmd)
1. [🚧 Work in Progress ⚠️] [Unsupervised Learning - Explore your Data with PCA](slides/76-unsupervised.qmd) 


# Tools

## R and Rstudio

You can run within Visual Studio Code, in the docker container provided by the summer school organizers.

Otherwise, you can also:

- Install R from [CRAN](https://cran.r-project.org/).
- Install the [Rstudio](https://www.rstudio.com/) interface. 


Remeber! R works with packages.

## Install a package

First install the package with `install.packages()` (you only have to do it once).


## Load a package

Then load it with `library()`, to make it's functions available. (you have to do it at the beginning of each of your scripts).



## Packages that we are going to use:

Please install this packages:

```r
install.packages(c('tidyverse', 'palmerpenguins', 'here', 'broom', 'janitor'))
```

and place this snippet of code in front of all your scripts.

```r
library(tidyverse)
library(here)
library(palmerpenguins)
library(broom)
library(janitor)
```

{{< include extra/books.qmd >}}

# Source Code

The source code for this course is [available on Github](https://github.com/othomantegazza/mawazo-summer-school/).
