---
title: "A Few words on Statistical Models"
subtitle: '[Home](../index.html) | [CBSER Summer School by Mawazo Institute](https://www.summercompschool.mawazoinstitute.org/)'
author: "Otho Mantegazza"
execute: 
  echo: true
format:
  html:
    toc: true
    number-sections: true
editor_options: 
  chunk_output_type: console
---

# Why Statistical Models

When you reach the limit of what graphical exploration and summary statistics can tell you, you can use statistical models to explore your data.

## Why?

When we look for **insights** in complex datasets, sometimes we want to know:

- Is there a **multivariate pattern** in the data? One that is evident only when we compare multiple variables at once.
- Are the patterns that we observe in data there **by chance**? If it they are not, we can start hypothesizing and exploring if they are **caused** by something.

## Which models?

### Supervised models

In the lesson on [supervised models](73-supervised.qmd), we will use **linear models** to test if we could **"predict"** the number of spikelets from the number primary branches and other features of rice panicles, i.e. to test if we could predict a **response** from a collection of **predictors**. 

### Unsupervised models

In the lesson on [unsupervised models](76-unsupervised.qmd), we will use **clustering** and **Principal Component Analysis** to explore if we can use multiple phenotypic features to group rice panicle in distinct sets that behave similarly; i.e. to detect multivariate patterns in the data.

# Resources

I will give you an overview on the topics mentioned above, but the best resources to study them in detail are the books in this list or any other book that you feel comfortable using:

- [Introduction to Statistical Learning](https://www.statlearning.com).
- [Introduction to Data Science](https://rafalab.github.io/dsbook/).
- [Tidy Modeling with R](https://www.tmwr.org/).
